services:
  postgres:
    image: postgres:16-alpine
    container_name: ny_taxi_postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  pipeline:
    build: .
    container_name: ny_taxi_pipeline
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./scripts:/app/scripts
      - ./sql:/app/sql

volumes:
  pgdata: